#############################################################################
# $Id$

Import('env')

sources = Split("""
   cameracontroller.cpp
   main.cpp
""")

if env['PLATFORM'] == 'win32':
   sources = sources + env.RES('game.rc')

includePaths = Split("""
   #engine/include
   #gui/include
   #tech/include
""")

libPaths = Split("""
   #allguids
   #tech
   #engine
   #gui
""")

linkLibs = Split("""
   allguids
   tech
   engine
   gui
""")

env = env.Copy()
env.UseGL()
env.UseLua()
env.UseTinyxml()
env.UseZLib()
env.BuildExecutable('game', sources, include_path=includePaths, lib_path=libPaths, libs=linkLibs)
