#############################################################################
# $Id$

Import('*')

sources = Split("""
   cameracontroller.cpp
   main.cpp
""")

if env['PLATFORM'] == 'win32':
   sources = sources + env.RES('game.rc')

includePaths = Split("""
   #engine/include
   #gui/include
   #render/include
   #tech/include
""")

libPaths = Split("""
   #allguids
   #tech
   #render
   #engine
   #gui
""")

libs = Split("""
   allguids
   tech
   rendergl
   engine
   gui
   user32
   kernel32
   gdi32
   winmm
""")

env = env.Copy()
env.Append(CPPPATH = includePaths)
env.Append(LIBPATH = libPaths)
env.Append(LIBS = libs)
env.UseGL()
env.UseLua()
env.UseTinyxml()
env.UseZLib()
if env.get('debug'):
   env['PDB'] = 'game.pdb'
env.Program('game', sources)
