#############################################################################
# $Id$

Import('*')

sources = Split("""
   guibasicrenderer.cpp
   guibeveledrenderer.cpp
   guibutton.cpp
   guicontext.cpp
   guidialog.cpp
   guielementenum.cpp
   guielementtools.cpp
   guievent.cpp
   guifontfactory.cpp
   guifactory.cpp
   guilabel.cpp
   guilayout.cpp
   guipanel.cpp
   guirender.cpp
   guistyle.cpp
   guitextedit.cpp
   guitypes.cpp
""")

includePaths = Split("""
   #3rdparty/sgi
   #3rdparty/glew/include
   #3rdparty/lua/include
   #3rdparty/tinyxml
   #engine/include
   #gui/include
   #tech/include
""") + glIncludePaths

if env['PLATFORM'] == 'win32':
   sources = sources + ['guifontw32.cpp']
elif env['PLATFORM'] == 'cygwin':
   sources = sources + ['guifontx11.cpp']

env = env.Copy()
env.Append(CPPPATH = includePaths)
env.Append(CPPDEFINES = ['STATIC_BUILD'])
env.Library('gui', sources)
