#############################################################################
# $Id$

Import('env')

sourceFiles = Split("""
   src/camera.cpp
   src/cmds.cpp
   src/engine.cpp
   src/entity.cpp
   src/entitymanager.cpp
   src/glinterleave.cpp
   src/gltexture.cpp
   src/input.cpp
   src/luainterp.cpp
   src/model.cpp
   src/modelanim.cpp
   src/modelms3d.cpp
   src/ms3dread.cpp
   src/renderer.cpp
   src/saveloadmanager.cpp
   src/sim.cpp
   src/syscommon.cpp
   src/terrain.cpp
   src/terrainrender.cpp
""")

if env['PLATFORM'] == 'win32':
   sourceFiles += ['src/syswin.cpp', 'src/soundwin.cpp']
elif env['PLATFORM'] == 'cygwin':
   sourceFiles += ['src/syslinux.cpp']

includePaths = Split("""
   #engine/include
   #tech/include
""")

libPaths = Split("""
   #allguids
   #tech
""")

linkLibs = Split("""
   allguids
   tech
""")

local = env.Copy()
local.UseGL()
local.UseLua()
local.UseTinyxml()
local.BuildLibrary(target='engine',
                   source=sourceFiles,
                   include_path=includePaths,
                   lib_path=libPaths,
                   libs=linkLibs)
