#############################################################################
# $Id$

Import('*')

sources = Split("""
   src/camera.cpp
   src/cmds.cpp
   src/engine.cpp
   src/entitymanager.cpp
   src/frustum.cpp
   src/glinterleave.cpp
   src/gltexture.cpp
   src/input.cpp
   src/luainterp.cpp
   src/model.cpp
   src/ms3dread.cpp
   src/ray.cpp
   src/saveloadmanager.cpp
   src/scene.cpp
   src/scenecamera.cpp
   src/sceneentity.cpp
   src/sceneentityenum.cpp
   src/scenelayer.cpp
   src/scriptvar.cpp
   src/sim.cpp
   src/terrain.cpp
   src/terrainrender.cpp
""")

if env['PLATFORM'] == 'win32':
   sources = sources + ['src/syswin.cpp', 'src/soundwin.cpp']
elif env['PLATFORM'] == 'cygwin':
   sources = sources + ['src/syslinux.cpp', 'src/soundnull.cpp']

includePaths = Split("""
   #engine/include
   #render/include
   #tech/include
""")

env = env.Copy()
env.Append(CPPPATH = includePaths)
env.UseGL()
env.UseLua()
env.UseTinyxml()
env.BuildLibrary('engine', sources)
