// $Id$

struct inputs
{
   float4 position   : POSITION;
   float3 normal     : NORMAL;
   float2 texCoord0  : TEXCOORD0;
};

struct outputs
{
   float4 position   : POSITION;
   float2 texCoord0  : TEXCOORD0;
   float4 color0     : COLOR0;
};

outputs main(inputs IN, 
             uniform float4x4 modelViewProj)
{
   outputs OUT;

   OUT.position = mul(modelViewProj, IN.position);
   OUT.texCoord0 = IN.texCoord0;
   OUT.color0 = 1;

   return OUT;
}
