#############################################################################
# $Id$

Import('env')

sourceFiles = Split("""
   allguids.cpp
""")

includePaths = Split("""
   #tech/include
   #render/include
   #engine/include
   #gui/include
   #game
   #editor
""")

local = env.Copy()
local.BuildStaticLibrary(target='allguids',
                         source=sourceFiles,
                         include_path=includePaths)
