#############################################################################
# $Id$

Import('env')

sourceFiles = Split("""
   src/freetypeutils.cpp
   src/glinterleave.cpp
   src/gltexture.cpp
   src/render2d.cpp
   src/renderer.cpp
   src/renderfontfreetype.cpp
   src/renderfontftgl.cpp
""")

if env['PLATFORM'] == 'win32':
   sourceFiles += ['src/renderfontw32.cpp']
elif env['PLATFORM'] == 'cygwin':
   sourceFiles += ['src/renderfontx11.cpp']

includePaths = Split("""
   #platform/include
   #rendergl/include
   #tech/include
""")

libPaths = Split("""
   #allguids
   #platform
   #tech
""")

linkLibs = Split("""
   allguids
   platform
   tech
""")

local = env.Copy()
local.UseFTGL()
local.BuildLibrary(target='rendergl',
                   source=sourceFiles,
                   include_path=includePaths,
                   lib_path=libPaths,
                   libs=linkLibs)
