#############################################################################
# $Id$

Import('env')

sourceFiles = Split("""
   src/freetypeutils.cpp
   src/glinterleave.cpp
   src/gltexture.cpp
   src/renderer.cpp
   src/renderfontfreetype.cpp
""")

includePaths = Split("""
   #rendergl/include
   #tech/include
""")

libPaths = Split("""
   #allguids
   #tech
""")

linkLibs = Split("""
   allguids
   tech
""")

local = env.Copy()
local.UseFTGL()
local.BuildLibrary(target='rendergl',
                   source=sourceFiles,
                   include_path=includePaths,
                   lib_path=libPaths,
                   libs=linkLibs)
