#############################################################################
# $Id$

Import('env')

sourceFiles = Split("""
   src/guibasicrenderer.cpp
   src/guibeveledrenderer.cpp
   src/guibutton.cpp
   src/guicontext.cpp
   src/guidialog.cpp
   src/guielementenum.cpp
   src/guielementtools.cpp
   src/guievent.cpp
   src/guieventrouter.cpp
   src/guieventsounds.cpp
   src/guifontfactory.cpp
   src/guifactory.cpp
   src/guilabel.cpp
   src/guilayout.cpp
   src/guilistbox.cpp
   src/guipage.cpp
   src/guipagelayout.cpp
   src/guipanel.cpp
   src/guiparse.cpp
   src/guirenderd3d.cpp
   src/guirendergl.cpp
   src/guiscript.cpp
   src/guiscrollbar.cpp
   src/guistyle.cpp
   src/guistylesheet.cpp
   src/guitextedit.cpp
   src/guitypes.cpp
""")

if env['PLATFORM'] == 'win32':
   sourceFiles += ['src/guifontw32.cpp', 'src/guifontd3d.cpp']
elif env['PLATFORM'] == 'cygwin':
   sourceFiles += ['src/guifontx11.cpp']

includePaths = Split("""
   #engine/include
   #gui/include
   #script/include
   #tech/include
""")

libPaths = Split("""
   #allguids
   #engine
   #script
   #tech
""")

linkLibs = Split("""
   allguids
   engine
   script
   tech
""")

local = env.Copy()
local.UseGL()
local.UseTinyxml()
local.BuildLibrary(target='gui',
                   source=sourceFiles,
                   include_path=includePaths,
                   lib_path=libPaths,
                   libs=linkLibs)
