#############################################################################
# $Id$

Import('env')

sources = Split("""
   src/guibasicrenderer.cpp
   src/guibeveledrenderer.cpp
   src/guibutton.cpp
   src/guicontext.cpp
   src/guidialog.cpp
   src/guielementenum.cpp
   src/guielementtools.cpp
   src/guievent.cpp
   src/guieventsounds.cpp
   src/guifontfactory.cpp
   src/guifactory.cpp
   src/guilabel.cpp
   src/guilayout.cpp
   src/guilistbox.cpp
   src/guipage.cpp
   src/guipanel.cpp
   src/guiparse.cpp
   src/guirender.cpp
   src/guirenderd3d.cpp
   src/guiscript.cpp
   src/guiscrollbar.cpp
   src/guistyle.cpp
   src/guistylesheet.cpp
   src/guitextedit.cpp
   src/guitypes.cpp
""")

if env['PLATFORM'] == 'win32':
   sources = sources + ['src/guifontw32.cpp', 'src/guifontd3d.cpp']
elif env['PLATFORM'] == 'cygwin':
   sources = sources + ['src/guifontx11.cpp']

includePaths = Split("""
   #engine/include
   #gui/include
   #tech/include
""")

libPaths = Split("""
   #allguids
   #tech
   #engine
""")

linkLibs = Split("""
   allguids
   tech
   engine
""")

env = env.Copy()
env.UseGL()
env.UseLua()
env.UseTinyxml()
env.BuildLibrary('gui', sources, include_path=includePaths, lib_path=libPaths, libs=linkLibs)
