#############################################################################
# $Id$

Import('env')

sourceFiles = Split("""
   src/netaddress.cpp
   src/netsocket.cpp
   src/network.cpp
""")

libPaths = Split("""
   #allguids
   #tech
""")

linkLibs = Split("""
   allguids
   tech
""")

if env['PLATFORM'] == 'win32':
   linkLibs += ['ws2_32.lib']

local = env.Copy()
local.BuildLibrary(target='network',
                   export_symbol='NET_EXPORTS',
                   source=sourceFiles,
                   lib_path=libPaths,
                   libs=linkLibs)
