#############################################################################
# $Id$

Import('env')

sourceFiles = Split("""
   Exporter.cpp
   ExportPreviewDlg.cpp
   IntermediateJoint.cpp
   msPlugInApp.cpp
   msPlugInImpl.cpp
   StdAfx.cpp
""")

includePaths = Split("""
   #MilkShapeExporter
   #engine/include
   #rendergl/include
   #tech/include
""")

libPaths = Split("""
   #MilkShapeExporter
   #allguids
   #tech
   #engine
""")

linkLibs = Split("""
   msModelLib.lib
   allguids.lib
   tech.lib
   engine.lib
   comdlg32.lib
""")

if env['PLATFORM'] == 'win32':
   local = env.Copy()
   local.UseNvTriStrip()
   local.UseTinyxml()
   local.UseZLib()
   local.BuildSharedLibrary(target='msSGEExporter',
                            source=sourceFiles + local.RES('msPlugIn.rc'),
                            deffile='#MilkShapeExporter/msPlugin.def',
                            include_path=includePaths,
                            lib_path=libPaths,
                            libs=linkLibs)
