#############################################################################
# $Id$

Import('env')

sources = Split("""
   aboutdlg.cpp
   BitmapUtils.cpp
   CameraDlg.cpp
   cmds.cpp
   DynamicLink.cpp
   editorApp.cpp
   editorCommands.cpp
   editorCtrlBars.cpp
   editorDoc.cpp
   editorTools.cpp
   editorTypes.cpp
   editorView.cpp
   LogWnd.cpp
   MainFrm.cpp
   MapPropertiesDlg.cpp
   MapSettingsDlg.cpp
   OutputBar.cpp
   scbarcf.cpp
   scbarg.cpp
   ScriptCmdDlg.cpp
   sizecbar.cpp
   splashwnd.cpp
   stdhdr.cpp
   ToolPalette.cpp
   ToolPaletteBar.cpp
""")

includePaths = Split("""
   #3rdparty/glew/include
   #3rdparty/Cg/include
   #3rdparty/lua/include
   #3rdparty/tinyxml
   #3rdparty/wtl/include
   #engine/include
   #tech/include
""")

libPaths = Split("""
   #allguids
   #tech
   #render
   #engine
""")

linkLibs = Split("""
   allguids.lib
   tech.lib
   engine.lib
   opengl32.lib
   glu32.lib
""")

local = env.Copy()
#local.Append(LINKFLAGS = ['/force:multiple'])
local.UseGL()
local.UseCg()
local.UseLua()
local.UseTinyxml()
local.UseZLib()
local.BuildExecutable('editor', sources + local.RES('editor.rc'), include_path=includePaths, lib_path=libPaths, libs=linkLibs)
