#############################################################################
# $Id$

Import('env')

sources = Split("""
   aboutdlg.cpp
   BitmapUtils.cpp
   cmds.cpp
   DynamicLink.cpp
   editorApp.cpp
   editorCommands.cpp
   editorCtrlBars.cpp
   editorDoc.cpp
   editorTools.cpp
   editorTypes.cpp
   editorView.cpp
   LogWnd.cpp
   MainFrm.cpp
   MapSettingsDlg.cpp
   OutputBar.cpp
   scbarcf.cpp
   scbarg.cpp
   ScriptCmdDlg.cpp
   sizecbar.cpp
   splashwnd.cpp
   stdhdr.cpp
   ToolPalette.cpp
   ToolPaletteBar.cpp
""")

includePaths = Split("""
   #3rdparty/glew/include
   #3rdparty/Cg/include
   #3rdparty/lua/include
   #3rdparty/tinyxml
   #3rdparty/wtl/include
   #engine/include
   #render/include
   #tech/include
""")

libPaths = Split("""
   #3rdparty/Cg/lib
   #3rdparty/glew
   #3rdparty/tinyxml
   #3rdparty/lua
   #3rdparty/zlib
   #allguids
   #tech
   #render
   #engine
""")

linkLibs = Split("""
   allguids.lib
   tech.lib
   rendergl.lib
   engine.lib
   lua.lib
   tinyxml.lib
   glew.lib
   zlibwapi.lib
   user32.lib
   kernel32.lib
   gdi32.lib
   winmm.lib
   opengl32.lib
   glu32.lib
   cg.lib
   cgGL.lib
""")

env = env.Copy()
env.Append(LINKFLAGS = ['/force:multiple'])
if env.get('debug'):
   env['PDB'] = 'editor.pdb'
env.BuildExecutable('editor', sources + env.RES('editor.rc'), include_path=includePaths, lib_path=libPaths, libs=linkLibs)
