#############################################################################
# $Id$

Import('env')

sourceFiles = Split("""
   aiagent.cpp
   aibehaviormoveto.cpp
   aibehaviorstand.cpp
   aibehaviorwander.cpp
""")

libPaths = Split("""
   #allguids
   #tech
""")

linkLibs = Split("""
   allguids
   tech
""")

local = env.Copy()
local.BuildLibrary(target='ai',
                   source=sourceFiles,
                   lib_path=libPaths,
                   libs=linkLibs)
