#############################################################################
# $Id$

Import('*')

sources = Split("""
   src/bmp.cpp
   src/comtools.cpp
   src/config.cpp
   src/cpufeatures.cpp
   src/dictionary.cpp
   src/dictionarystore.cpp
   src/fileenum.cpp
   src/filepath.cpp
   src/filespec.cpp
   src/functor.cpp
   src/globalobjreg.cpp
   src/graphtest.cpp
   src/hash.cpp
   src/image.cpp
   src/log.cpp
   src/matrix4.cpp
   src/quat.cpp
   src/readwritefile.cpp
   src/readwritemem.cpp
   src/resourcemanager.cpp
   src/techdebug.cpp
   src/techmath.cpp
   src/techstring.cpp
   src/techtime.cpp
   src/text.cpp
   src/tga.cpp
   src/thread.cpp
   src/threadcaller.cpp
""")

includePaths = Split("""
   #tech/include
""")

env = env.Copy()
env.UseZLib()
env.Append(CPPPATH = includePaths)
env.Library('tech', sources)
