#############################################################################
# $Id$

Import('env')

sourceFiles = Split("""
   src/luainterp.cpp
   src/luastate.cpp
   src/luautil.cpp
""")

includePaths = Split("""
   #script/include
   #tech/include
""")

libPaths = Split("""
   #allguids
   #tech
""")

linkLibs = Split("""
   allguids
   tech
""")

local = env.Copy()
local.UseLua()
local.UseTinyxml()
local.BuildLibrary(target='script',
                   source=sourceFiles,
                   include_path=includePaths,
                   lib_path=libPaths,
                   libs=linkLibs)
