#############################################################################
# $Id$

Import('*')

sources = Split("""
   bmp.cpp
   comtools.cpp
   config.cpp
   cpufeatures.cpp
   dictionary.cpp
   dictionarystore.cpp
   fileiter.cpp
   filepath.cpp
   filespec.cpp
   filereadwrite.cpp
   functor.cpp
   globalobjreg.cpp
   graphtest.cpp
   hash.cpp
   imagedata.cpp
   log.cpp
   matrix4.cpp
   memmanager.cpp
   prime.cpp
   quat.cpp
   rand.cpp
   readwritemem.cpp
   resourcemanager.cpp
   techdebug.cpp
   techstring.cpp
   techtime.cpp
   text.cpp
   tga.cpp
   thread.cpp
   threadcaller.cpp
""")

includePaths = Split("""
   #tech/include
   #3rdparty/zlib
   #3rdparty/zlib/contrib/minizip
""")

env = env.Copy()
env.Append(CPPPATH = includePaths)
env.Append(CPPDEFINES = ['STATIC_BUILD'])
env.Library('tech', sources)
